version: 1.1.{build}.0

artifacts:
  - path: mandelbrot_cpp_viewer.7z
    name: mandelbrot_cpp_viewer.7z

deploy:
  release: mandelbrot_cpp_viewer-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release via Appveyor on push'
  provider: GitHub
  auth_token:
    secure: FeBOyWj8jfeUe7rzAM0ffdKbpnVQgLb5BxB6yrqWOzC/UoBi1JDbUdWxyQnjK1SA
  artifact: mandelbrot_cpp_viewer.7z
  draft: false
  prerelease: false
  skip_tags: true
  on:
    branch: main

init:
  - cmake --version

build_script:
  - git clone https://github.com/SFML/SFML.git
  - cd SFML &&  mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - dir lib\Release
  - cd ../../ && mkdir build && cd build
  - cmake .. -DSFML_DIR="SFML/build/" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - dir Release && cd ..
  - 7z a mandelbrot_cpp_viewer.7z build/Release/
